## ------------------------------------------------------------------
## Multivariate ASG
## ------------------------------------------------------------------

dim1_gibbs_sample_ASG <- function(ker, n_samples = 10 , burn_in = 2, thin = 1,
                                  theta_init, tol = 0.01, scale0 = 1,
                                  make_plots = TRUE) {
  start_time <- Sys.time()
  m <- 1
  total_iter <- burn_in + n_samples * thin
  theta_chain <- matrix(NA_real_, nrow = total_iter, ncol = m)
  colnames(theta_chain) <- paste0("theta_", seq_len(m))
  theta_new <- as.numeric(theta_init)
  
  ## Precompute broad proposal boxes and a normalized 1D density (for overlay) for each coord at t=1
  bounds_list <- vector("list", m)
  f_list <- vector("list", m)
  for (i in seq_len(m)) {
    g_i <- (function(i) {
      function(xi) {
        tmp <- theta_new
        tmp[i] <- xi
        ker(tmp)
      }
    })(i)
    bnds <- effective.support(g_i, tol = tol/m, scale0 = scale0)
    bounds_list[[i]] <- c(a = bnds$lower, b = bnds$upper)
    f_list[[i]] <- bnds$f         # normalized density over R (or approx support)
  }
  
  ## Sampling
  for (t in seq_len(total_iter)) {
    ## ONE u for the full sweep
    u <- runif(1, 0, ker(theta_new))
    for (i in seq_len(m)) {
      g_i <- (function(i) {
        function(xi) {
          tmp <- theta_new
          tmp[i] <- xi
          ker(tmp)
        }
      })(i)
      a_i <- bounds_list[[i]]["a"]; b_i <- bounds_list[[i]]["b"]
      theta_new[i] <- slice1d_fixed_u(g_i, u, a = a_i, b = b_i)
    }
    theta_chain[t, ] <- theta_new
  }
  
  sample_idx <- seq(from = burn_in + 1L, to = total_iter, by = thin)
  theta_samples <- theta_chain[sample_idx, , drop = FALSE]
  end_time <- Sys.time()
  time_taken <- as.numeric(difftime(end_time, start_time, units = "secs"))
  
  ## -----------------------
  ## Plots (per dimension)
  ## -----------------------
  if (make_plots) {
    for (i in seq_len(m)) {
      chain_i <- theta_chain[, i]
      samples_i <- theta_samples[, i]
      a <- bounds_list[[i]]["a"]; b <- bounds_list[[i]]["b"]
      f <- f_list[[i]]
      
      ## 1) Histogram + (initial-conditional) target line + bounds
      xs <- seq(a, b, length.out = 2000)
      df_target <- data.frame(x = xs, dens = f(xs))
      p_density <- ggplot() +
        geom_histogram(aes(x = samples_i, y = after_stat(density)), bins = 50, fill = "skyblue", color = "black", alpha = 0.7) +
        geom_line(data = df_target, aes(x = x, y = dens), linewidth = 2, color = "red") +
        geom_vline(xintercept = c(a, b), linetype = "dashed") +
        labs(title = paste("Dim", i, ": Samples Generated by ASG Desity plot"),
             x = paste0("theta_", i), y = "Density") +
        theme_minimal(base_size = 12) +
        annotate("text", x = min(samples_i, na.rm = TRUE), y = Inf,
                 label = sprintf("Time: %.2fs", time_taken),
                 hjust = 0, vjust = 1.2, size = 4)
      
      ## 2) Trace
      df_trace <- data.frame(iter = seq_along(chain_i), val = chain_i)
      p_trace <- ggplot(df_trace, aes(iter, val)) +
        geom_line(alpha = 0.8, size = 1.5) +
        geom_vline(xintercept = burn_in, linetype = "dashed", color = "red") +
        labs(title = paste("Dim", i, ": Trace"), x = "Iteration", y = paste0("theta_", i)) +
        theme_minimal(base_size = 12)
      
      ## 3) ACF (lag.max = 40)
      acf_vals <- acf(chain_i, plot = FALSE, lag.max = 50)
      df_acf <- data.frame(lag = as.numeric(acf_vals$lag),
                           acf = as.numeric(acf_vals$acf))
      p_acf <- ggplot(df_acf, aes(lag, acf)) +
        geom_hline(yintercept = 0) +
        geom_segment(aes(xend = lag, yend = 0)) +
        labs(title = paste("Dim", i, ": ACF"), x = "Lag", y = "ACF") +
        theme_minimal(base_size = 12)
      
      ## 4) Running mean
      rmn <- cumsum(chain_i) / seq_along(chain_i)
      df_rm <- data.frame(iter = seq_along(chain_i), mean = rmn)
      p_rm <- ggplot(df_rm, aes(iter, mean)) +
        geom_line(size = 2) +
        geom_vline(xintercept = burn_in, linetype = "dashed", color = "red") +
        labs(title = paste("Dim", i, ": Running mean"), x = "Iteration", y = "Mean") +
        theme_minimal(base_size = 12)
      
      ## Print (you can arrange with gridExtra if you like)
      print(p_density); print(p_trace); print(p_acf); print(p_rm)
    }
  }
  list(samples = theta_samples, chain = theta_chain,
       burn_in = burn_in, thin = thin, time_taken = time_taken)
}


multivariate_gibbs_sample_ASG <- function(ker, n_samples = 10, burn_in = 2, thin = 1,
                                          theta_init, tol = 0.01, scale0 = 1,
                                          make_plots = TRUE) {
  start_time <- Sys.time()
  m <- length(theta_init)
  total_iter <- burn_in + n_samples * thin
  theta_chain <- matrix(NA_real_, nrow = total_iter, ncol = m)
  colnames(theta_chain) <- paste0("theta_", seq_len(m))
  theta_new <- as.numeric(theta_init)
  
  for (t in seq_len(total_iter)) {
    
    u <- runif(1, 0, ker(theta_new))
    
    for (i in seq_len(m)) {
      
      g_i <- (function(i) {
        function(xi) {
          tmp <- theta_new
          tmp[i] <- xi
          ker(tmp)
        }
      })(i)
      
      # Recompute support for CURRENT conditional
      bnds <- effective.support(
        g_i,
        tol = tol/m,
        scale0 = scale0
      )
      
      a_i <- bnds$lower
      b_i <- bnds$upper
      
      # Slice draw using current conditional and current bracket
      theta_new[i] <- slice1d_fixed_u(
        g_i,
        u,
        a = a_i,
        b = b_i
      )
    }
    
    theta_chain[t, ] <- theta_new
  }
  
  sample_idx <- seq(from = burn_in + 1L, to = total_iter, by = thin)
  theta_samples <- theta_chain[sample_idx, , drop = FALSE]
  end_time <- Sys.time()
  time_taken <- as.numeric(difftime(end_time, start_time, units = "secs"))
  
  ## -----------------------------------------
  ## Diagnostics plots (single representative series)
  ## -----------------------------------------
  if (make_plots) {
    ## choose 1D summary to monitor
    diag_series <- theta_chain[, 1]
    series_name <- colnames(theta_chain)[1]
    
    # Trace plot
    df_trace <- data.frame(
      iter = seq_along(diag_series),
      val  = diag_series
    )
    p_trace <- ggplot(df_trace, aes(x = iter, y = val)) +
      geom_line(alpha = 0.8, size = 1.5) +
      geom_vline(xintercept = burn_in, linetype = "dashed", color = "red") +
      labs(
        title = "Trace for theta (first coordinate)",
        x = "Iteration",
        y = series_name
      ) +
      theme_minimal(base_size = 12) +
      coord_cartesian(ylim = c(-8, 8))
    
    # ACF plot (lag.max = 50)
    acf_vals <- acf(diag_series, plot = FALSE, lag.max = 50)
    df_acf <- data.frame(
      lag = as.numeric(acf_vals$lag),
      acf = as.numeric(acf_vals$acf)
    )
    p_acf <- ggplot(df_acf, aes(x = lag, y = acf)) +
      geom_hline(yintercept = 0, size = 1) +
      geom_segment(aes(xend = lag, yend = 0)) +
      labs(
        title = "ACF for theta (first coordinate)",
        x = "Lag",
        y = "ACF"
      ) +
      theme_minimal(base_size = 12)
    
    # Running mean plot
    running_mean <- cumsum(diag_series) / seq_along(diag_series)
    df_rm <- data.frame(
      iter = seq_along(diag_series),
      mean = running_mean
    )
    p_rm <- ggplot(df_rm, aes(x = iter, y = mean)) +
      geom_line(size = 2) +
      geom_vline(xintercept = burn_in, linetype = "dashed", color = "red") +
      labs(
        title = "Running mean for theta (first coordinate)",
        x = "Iteration",
        y = "Running mean"
      ) +
      theme_minimal(base_size = 12)
    
    print(p_trace)
    print(p_acf)
    print(p_rm)
    
    ## -----------------------------------------
    ## Log-kernel diagnostics for appendix
    ## log K(theta^(t)) from the full multivariate chain
    ## -----------------------------------------
    tiny <- 1e-300
    logK_series <- apply(theta_chain, 1, function(th) {
      val <- ker(as.numeric(th))
      log(pmax(val, tiny))  # log K(x^{(t)})
    })
    
    # Trace of log K(theta^{(t)})
    df_logk_trace <- data.frame(
      iter = seq_along(logK_series),
      logK = logK_series
    )
    p_logk_trace <- ggplot(df_logk_trace, aes(x = iter, y = logK)) +
      geom_line(alpha = 0.8, size = 2) +
      geom_vline(xintercept = burn_in, linetype = "dashed", color = "red") +
      labs(
        title = "Trace of log-kernel: log K(theta^{(t)})",
        x = "Iteration t",
        y = "log K(theta)"
      ) +
      theme_minimal(base_size = 12)
    
    # ACF of log K(theta^{(t)}) (again, use post–burn-in part)
    acf_logk <- acf(logK_series[(burn_in + 1L):length(logK_series)],
                    plot = FALSE, lag.max = 50)
    df_logk_acf <- data.frame(
      lag = as.numeric(acf_logk$lag),
      acf = as.numeric(acf_logk$acf)
    )
    p_logk_acf <- ggplot(df_logk_acf, aes(x = lag, y = acf)) +
      geom_hline(yintercept = 0, size = 2) +
      geom_segment(aes(xend = lag, yend = 0)) +
      labs(
        title = "ACF of log-kernel: log K(theta^{(t)})",
        x = "Lag",
        y = "ACF"
      ) +
      theme_minimal(base_size = 12)
    
    print(p_logk_trace)
    print(p_logk_acf)
  }
  
  ## -----------------------------------------
  ## Return
  ## -----------------------------------------
  list(
    samples     = theta_samples,
    chain       = theta_chain,
    burn_in     = burn_in,
    thin        = thin,
    time_taken  = time_taken
  )
}
